"""update_store

Revision ID: 3802af4b9cd9
Revises: 11eef5c897e6
Create Date: 2024-10-14 22:28:46.399926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3802af4b9cd9'
down_revision: Union[str, None] = '11eef5c897e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('order', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('order', sa.Column('reserved_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['id'])
    op.add_column('order_item', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('order_item', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('order_item', sa.Column('discount', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order_item', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_column('order_item', 'discount')
    op.drop_column('order_item', 'price')
    op.drop_column('order_item', 'user_id')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'confirmed_at')
    op.drop_column('order', 'reserved_at')
    op.drop_column('order', 'created_at')
    op.drop_column('order', 'user_id')
    # ### end Alembic commands ###
