"""fix_order_discount

Revision ID: 87a491b3e31a
Revises: 20385592b372
Create Date: 2024-10-16 00:14:34.223497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a491b3e31a'
down_revision: Union[str, None] = '20385592b372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'discount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'discount',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
