"""more_simplify_order

Revision ID: 88f5af948508
Revises: 4ea71324d254
Create Date: 2024-10-15 22:13:12.341224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88f5af948508'
down_revision: Union[str, None] = '4ea71324d254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'confirmed_at')
    op.drop_column('order', 'reserved_at')
    op.drop_column('order', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('reserved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
