"""set_ondelete

Revision ID: c379c34f307b
Revises: 88f5af948508
Create Date: 2024-10-15 22:17:43.024539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c379c34f307b'
down_revision: Union[str, None] = '88f5af948508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('name', sa.String(length=255), nullable=False))
    op.alter_column('order', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('order_item_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'item', ['item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_item_id_fkey', 'order', 'item', ['item_id'], ['id'])
    op.alter_column('order', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('order', 'name')
    # ### end Alembic commands ###
